version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: fastapi
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo:
